---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: soulmask-ops-web
  namespace: soulmask
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: soulmask-ops-web
  namespace: soulmask
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: soulmask-ops-web
  namespace: soulmask
subjects:
  - kind: ServiceAccount
    name: soulmask-ops-web
    namespace: soulmask
roleRef:
  kind: Role
  name: soulmask-ops-web
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: soulmask-ops-web-metrics
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: soulmask-ops-web-metrics
subjects:
  - kind: ServiceAccount
    name: soulmask-ops-web
    namespace: soulmask
roleRef:
  kind: ClusterRole
  name: soulmask-ops-web-metrics
  apiGroup: rbac.authorization.k8s.io
